### ISSUE TITLE
[Feature Request] - RGB, set colour

### ISSUE THREAD

**Issue by dmanlfc** [ShadowBlip/ayn-platform#7]
Thanks for creating this module, it helps a lot for these devices!

It would be great to be able to choose the RGB colour.
I haven't found how to do that with the current options.

Thanks in advance.

**Comment by pastaq** [comment]
Color selection would be done in a userspace tool. This is just a kernel driver that exposes the capabilities, it's not really intended for direct manipulation by users. That being said, you can manually change the color by following the instructions in the readme.

I plan on making an interface in OpenGamepadUI for this capability, but that will be separate to this project.

**Comment by dmanlfc** [comment]
Thanks @pastaq obviously i'm being extremely thick as I cannot change the colour... can you elaborate with an example?

**Comment by pastaq** [comment]
If you want red you would run

`echo 1 | sudo tee /sys/class/leds/multicolor:chassis/device/led_mode` to enable manual control

`echo 255 0 0 | sudo tee /sys/class/leds/multicolor:chassis/multi_intensity` will set the color. Change these three for the amount of red, green, and blue light respectively.

`echo 255 | sudo tee /sys/class/leds/multicolor:chassis/brightness` will set it to max brightness. Lower this for a softer light.

If you add these to a scripta and then launch that script with systems it will be able to set the color at boot. The device forgets the last setting after sleep or powering off.

**Comment by dmanlfc** [comment]
Thanks @pastaq I will check it out

**Comment by dmanlfc** [comment]
excellent, i was missing the `echo 255 | sudo tee /sys/class/leds/multicolor:chassis/brightness` command which is required after setting the `multi_intensity`
